version = 1
SPDX-PackageName = "community"
SPDX-PackageDownloadLocation = "https://github.com/openmfp/community"

[[annotations]]
path = "**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2025 SAP SE or an SAP affiliate company and openMFP contributors and portal contributors."
SPDX-License-Identifier = "Apache-2.0"